//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoWantsToBeMilionaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyQuiz
    {
        public int Id { get; set; }
        public string question { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string trueAnswer { get; set; }
        public int level { get; set; }
    }
}
